### ISSUE TITLE
Python的sort方法使用的是timsort

### ISSUE THREAD

**Issue by NNReka** [NEUP-Net-Depart/P-2024-plan#38]
### 你好
我在[文档](https://github.com/NEUP-Net-Depart/P-2024-plan/blob/master/Midterm/README.md#resources)中注意到，提到 Python 默认使用快速排序（Quicksort）作为其排序算法。这是不正确的。

Python 的 `list.sort()` 方法和内置的 `sorted()` 函数实际上使用的是 **Timsort**，这是一种结合了归并排序和插入排序的混合排序算法。Timsort 设计用于处理各种实际数据集，并且是一种稳定的排序算法。

### 详见
- [Python 排序指南：了解 Timsort](https://docs.python.org/3/howto/sorting.html#sort-stability-and-complex-sorts)

Python 文档中提到：“Python 裡使用的 Timsort 演算法，因為能利用資料集裡已經有的順序，可以有效率地做多次排序。”

突发奇想的捉虫，感谢你的付出。

**Comment by 17999824wyj** [comment]
好的，后续会进行修改。这个主要是我记错了:(
java里的sort有一部分默认用的是快排，我记混了
